var annotated_dup =
[
    [ "cldnn", null, [
      [ "detail", null, [
        [ "build_option_traits", "structcldnn_1_1detail_1_1build__option__traits.html", "structcldnn_1_1detail_1_1build__option__traits" ]
      ] ],
      [ "details", "namespacecldnn_1_1details.html", "namespacecldnn_1_1details" ],
      [ "instrumentation", null, [
        [ "profiling_info", "group__cpp__event.html#structcldnn_1_1instrumentation_1_1profiling__info", "group__cpp__event_structcldnn_1_1instrumentation_1_1profiling__info" ],
        [ "profiling_interval", "group__cpp__event.html#structcldnn_1_1instrumentation_1_1profiling__interval", "group__cpp__event_structcldnn_1_1instrumentation_1_1profiling__interval" ],
        [ "profiling_period", "structcldnn_1_1instrumentation_1_1profiling__period.html", "structcldnn_1_1instrumentation_1_1profiling__period" ],
        [ "profiling_period_basic", "structcldnn_1_1instrumentation_1_1profiling__period__basic.html", "structcldnn_1_1instrumentation_1_1profiling__period__basic" ],
        [ "timer", "classcldnn_1_1instrumentation_1_1timer.html", "classcldnn_1_1instrumentation_1_1timer" ]
      ] ],
      [ "meta", null, [
        [ "all", "structcldnn_1_1meta_1_1all.html", null ],
        [ "all< Val, Values... >", "structcldnn_1_1meta_1_1all_3_01_val_00_01_values_8_8_8_01_4.html", null ],
        [ "always_false_ty_val", "structcldnn_1_1meta_1_1always__false__ty__val.html", null ],
        [ "is_any_of", "structcldnn_1_1meta_1_1is__any__of.html", null ],
        [ "is_any_of< T, U, Rest... >", "structcldnn_1_1meta_1_1is__any__of_3_01_t_00_01_u_00_01_rest_8_8_8_01_4.html", null ],
        [ "val_tuple", "structcldnn_1_1meta_1_1val__tuple.html", null ]
      ] ],
      [ "activation", "structcldnn_1_1activation.html", "structcldnn_1_1activation" ],
      [ "batch_norm", "structcldnn_1_1batch__norm.html", "structcldnn_1_1batch__norm" ],
      [ "build_option", "structcldnn_1_1build__option.html", "structcldnn_1_1build__option" ],
      [ "build_option_bool", "structcldnn_1_1build__option__bool.html", "structcldnn_1_1build__option__bool" ],
      [ "build_option_directory", "structcldnn_1_1build__option__directory.html", "structcldnn_1_1build__option__directory" ],
      [ "build_option_outputs", "structcldnn_1_1build__option__outputs.html", "structcldnn_1_1build__option__outputs" ],
      [ "build_option_tuning_config", "structcldnn_1_1build__option__tuning__config.html", "structcldnn_1_1build__option__tuning__config" ],
      [ "build_options", "classcldnn_1_1build__options.html", "classcldnn_1_1build__options" ],
      [ "concatenation", "structcldnn_1_1concatenation.html", "structcldnn_1_1concatenation" ],
      [ "convolution", "structcldnn_1_1convolution.html", "structcldnn_1_1convolution" ],
      [ "crop", "structcldnn_1_1crop.html", "structcldnn_1_1crop" ],
      [ "custom_gpu_primitive", "structcldnn_1_1custom__gpu__primitive.html", "structcldnn_1_1custom__gpu__primitive" ],
      [ "data", "structcldnn_1_1data.html", "structcldnn_1_1data" ],
      [ "data_type_to_type", "group__cpp__memory.html#structcldnn_1_1data__type__to__type", null ],
      [ "data_type_traits", "structcldnn_1_1data__type__traits.html", null ],
      [ "deconvolution", "structcldnn_1_1deconvolution.html", "structcldnn_1_1deconvolution" ],
      [ "detection_output", "structcldnn_1_1detection__output.html", "structcldnn_1_1detection__output" ],
      [ "eltwise", "structcldnn_1_1eltwise.html", "structcldnn_1_1eltwise" ],
      [ "engine", "structcldnn_1_1engine.html", "structcldnn_1_1engine" ],
      [ "engine_configuration", "structcldnn_1_1engine__configuration.html", "structcldnn_1_1engine__configuration" ],
      [ "error", "classcldnn_1_1error.html", "classcldnn_1_1error" ],
      [ "event", "structcldnn_1_1event.html", "structcldnn_1_1event" ],
      [ "format", "structcldnn_1_1format.html", "structcldnn_1_1format" ],
      [ "format_traits", "structcldnn_1_1format__traits.html", "structcldnn_1_1format__traits" ],
      [ "fully_connected", "structcldnn_1_1fully__connected.html", "structcldnn_1_1fully__connected" ],
      [ "half_impl", "classcldnn_1_1half__impl.html", "classcldnn_1_1half__impl" ],
      [ "input_layout", "structcldnn_1_1input__layout.html", "structcldnn_1_1input__layout" ],
      [ "layout", "structcldnn_1_1layout.html", "structcldnn_1_1layout" ],
      [ "lrn", "structcldnn_1_1lrn.html", "structcldnn_1_1lrn" ],
      [ "memory", "structcldnn_1_1memory.html", "structcldnn_1_1memory" ],
      [ "network", "structcldnn_1_1network.html", "structcldnn_1_1network" ],
      [ "network_output", "structcldnn_1_1network__output.html", "structcldnn_1_1network__output" ],
      [ "normalize", "structcldnn_1_1normalize.html", "structcldnn_1_1normalize" ],
      [ "padding", "structcldnn_1_1padding.html", "structcldnn_1_1padding" ],
      [ "permute", "structcldnn_1_1permute.html", "structcldnn_1_1permute" ],
      [ "pointer", "structcldnn_1_1pointer.html", "structcldnn_1_1pointer" ],
      [ "pooling", "structcldnn_1_1pooling.html", "structcldnn_1_1pooling" ],
      [ "primitive", "structcldnn_1_1primitive.html", "structcldnn_1_1primitive" ],
      [ "primitive_base", "classcldnn_1_1primitive__base.html", "classcldnn_1_1primitive__base" ],
      [ "prior_box", "structcldnn_1_1prior__box.html", "structcldnn_1_1prior__box" ],
      [ "program", "structcldnn_1_1program.html", "structcldnn_1_1program" ],
      [ "proposal", "structcldnn_1_1proposal.html", "structcldnn_1_1proposal" ],
      [ "reorder", "structcldnn_1_1reorder.html", "structcldnn_1_1reorder" ],
      [ "reshape", "structcldnn_1_1reshape.html", "structcldnn_1_1reshape" ],
      [ "roi_pooling", "structcldnn_1_1roi__pooling.html", "structcldnn_1_1roi__pooling" ],
      [ "scale", "structcldnn_1_1scale.html", "structcldnn_1_1scale" ],
      [ "softmax", "structcldnn_1_1softmax.html", "structcldnn_1_1softmax" ],
      [ "tensor", "structcldnn_1_1tensor.html", "structcldnn_1_1tensor" ],
      [ "topology", "structcldnn_1_1topology.html", "structcldnn_1_1topology" ],
      [ "tuning_config_options", "structcldnn_1_1tuning__config__options.html", "structcldnn_1_1tuning__config__options" ],
      [ "type_to_data_type", "group__cpp__memory.html#structcldnn_1_1type__to__data__type", null ]
    ] ],
    [ "cldnn_activation_additional_params", "group__c__topology.html#structcldnn__activation__additional__params", "group__c__topology_structcldnn__activation__additional__params" ],
    [ "cldnn_activation_desc", "group__c__primitives.html#structcldnn__activation__desc", "group__c__primitives_structcldnn__activation__desc" ],
    [ "cldnn_arg", "group__c__topology.html#structcldnn__arg", "group__c__topology_structcldnn__arg" ],
    [ "cldnn_batch_norm_desc", "group__c__primitives.html#structcldnn__batch__norm__desc", "group__c__primitives_structcldnn__batch__norm__desc" ],
    [ "cldnn_build_option", "group__c__network.html#structcldnn__build__option", "group__c__network_structcldnn__build__option" ],
    [ "cldnn_concatenation_desc", "group__c__primitives.html#structcldnn__concatenation__desc", "group__c__primitives_structcldnn__concatenation__desc" ],
    [ "cldnn_convolution_desc", "group__c__primitives.html#structcldnn__convolution__desc", "group__c__primitives_structcldnn__convolution__desc" ],
    [ "cldnn_crop_desc", "group__c__primitives.html#structcldnn__crop__desc", "group__c__primitives_structcldnn__crop__desc" ],
    [ "cldnn_custom_gpu_primitive_desc", "group__c__primitives.html#structcldnn__custom__gpu__primitive__desc", "group__c__primitives_structcldnn__custom__gpu__primitive__desc" ],
    [ "cldnn_data_desc", "group__c__primitives.html#structcldnn__data__desc", "group__c__primitives_structcldnn__data__desc" ],
    [ "cldnn_deconvolution_desc", "group__c__primitives.html#structcldnn__deconvolution__desc", "group__c__primitives_structcldnn__deconvolution__desc" ],
    [ "cldnn_detection_output_desc", "group__c__primitives.html#structcldnn__detection__output__desc", "group__c__primitives_structcldnn__detection__output__desc" ],
    [ "cldnn_eltwise_desc", "group__c__primitives.html#structcldnn__eltwise__desc", "group__c__primitives_structcldnn__eltwise__desc" ],
    [ "cldnn_engine_configuration", "group__c__engine.html#structcldnn__engine__configuration", "group__c__engine_structcldnn__engine__configuration" ],
    [ "cldnn_engine_info", "group__c__engine.html#structcldnn__engine__info", "group__c__engine_structcldnn__engine__info" ],
    [ "cldnn_float_arr", "group__c__topology.html#structcldnn__float__arr", "group__c__topology_structcldnn__float__arr" ],
    [ "cldnn_fully_connected_desc", "group__c__primitives.html#structcldnn__fully__connected__desc", "group__c__primitives_structcldnn__fully__connected__desc" ],
    [ "cldnn_input_layout_desc", "group__c__primitives.html#structcldnn__input__layout__desc", "group__c__primitives_structcldnn__input__layout__desc" ],
    [ "cldnn_layout", "group__c__memory.html#structcldnn__layout", "group__c__memory_structcldnn__layout" ],
    [ "cldnn_lrn_desc", "group__c__primitives.html#structcldnn__lrn__desc", "group__c__primitives_structcldnn__lrn__desc" ],
    [ "cldnn_network_output", "group__c__network.html#structcldnn__network__output", "group__c__network_structcldnn__network__output" ],
    [ "cldnn_normalize_desc", "group__c__primitives.html#structcldnn__normalize__desc", "group__c__primitives_structcldnn__normalize__desc" ],
    [ "cldnn_padding", "group__c__memory.html#structcldnn__padding", "group__c__memory_structcldnn__padding" ],
    [ "cldnn_permute_desc", "group__c__primitives.html#structcldnn__permute__desc", "group__c__primitives_structcldnn__permute__desc" ],
    [ "cldnn_pooling_desc", "group__c__primitives.html#structcldnn__pooling__desc", "group__c__primitives_structcldnn__pooling__desc" ],
    [ "cldnn_primitive_desc", "group__c__topology.html#structcldnn__primitive__desc", "group__c__topology_structcldnn__primitive__desc" ],
    [ "cldnn_primitive_id_arr", "group__c__topology.html#structcldnn__primitive__id__arr", "group__c__topology_structcldnn__primitive__id__arr" ],
    [ "cldnn_prior_box_desc", "group__c__primitives.html#structcldnn__prior__box__desc", "group__c__primitives_structcldnn__prior__box__desc" ],
    [ "cldnn_profiling_interval", "group__c__network.html#structcldnn__profiling__interval", "group__c__network_structcldnn__profiling__interval" ],
    [ "cldnn_proposal_desc", "group__c__primitives.html#structcldnn__proposal__desc", "group__c__primitives_structcldnn__proposal__desc" ],
    [ "cldnn_reorder_desc", "group__c__primitives.html#structcldnn__reorder__desc", "group__c__primitives_structcldnn__reorder__desc" ],
    [ "cldnn_reshape_desc", "group__c__primitives.html#structcldnn__reshape__desc", "group__c__primitives_structcldnn__reshape__desc" ],
    [ "cldnn_roi_pooling_desc", "group__c__primitives.html#structcldnn__roi__pooling__desc", "group__c__primitives_structcldnn__roi__pooling__desc" ],
    [ "cldnn_scale_desc", "group__c__primitives.html#structcldnn__scale__desc", "group__c__primitives_structcldnn__scale__desc" ],
    [ "cldnn_softmax_desc", "group__c__primitives.html#structcldnn__softmax__desc", "group__c__primitives_structcldnn__softmax__desc" ],
    [ "cldnn_tensor", "group__c__memory.html#structcldnn__tensor", "group__c__memory_structcldnn__tensor" ],
    [ "cldnn_tuning_config", "group__c__network.html#structcldnn__tuning__config", "group__c__network_structcldnn__tuning__config" ],
    [ "cldnn_uint16_t_arr", "group__c__topology.html#structcldnn__uint16__t__arr", "group__c__topology_structcldnn__uint16__t__arr" ]
];